name: cuidapet_api
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  dotenv: ^4.2.0
  mysql1: ^0.20.0
  get_it: ^8.0.3
  logger: ^2.4.0
  injectable: ^2.4.4
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.6
  http: ^1.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  mocktail: ^1.0.4
  injectable_generator: ^2.6.2
  build_runner: ^2.4.11
  shelf_router_generator: ^1.1.0
